services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'

    _instanceof:
        App\Domain\Specification\SkipSpecification:
            tags: ['app.skip_specification']

    App\Domain\Repository\ProductRepositoryInterface:
        alias: App\Infrastructure\Repository\ProductRepository

    App\Domain\Repository\Flusher:
        alias: App\Infrastructure\Repository\ProductRepository

    App\Application\Import\ProductImporter:
        arguments:
            $specifications: !tagged_iterator app.skip_specification
            $clock: '@clock'
